FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Copiar build del frontend
COPY frontend-build/ .

# Copiar configuración de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
